"""empty message

Revision ID: 6a8ce0536b12
Revises: dba98e8785e7
Create Date: 2019-07-04 16:47:32.605385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a8ce0536b12'
down_revision = 'dba98e8785e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('filename', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'filename')
    # ### end Alembic commands ###
