"""empty message

Revision ID: dba98e8785e7
Revises: 
Create Date: 2019-07-04 16:11:32.560287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dba98e8785e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('zsyear', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zsyear')
    )
    op.create_table('zs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_name', sa.String(length=225), nullable=False),
    sa.Column('education_number', sa.String(length=225), nullable=False),
    sa.Column('sex_name', sa.String(length=225), nullable=False),
    sa.Column('id_card', sa.String(length=225), nullable=False),
    sa.Column('total_score_of_filing', sa.Integer(), nullable=False),
    sa.Column('ranking', sa.String(length=255), nullable=True),
    sa.Column('major_name', sa.String(length=225), nullable=False),
    sa.Column('report', sa.String(length=225), nullable=True),
    sa.Column('report_for_cancel', sa.String(length=225), nullable=True),
    sa.Column('student_address', sa.String(length=225), nullable=True),
    sa.Column('graduation_secondary_school_name', sa.String(length=225), nullable=True),
    sa.Column('nation_name', sa.String(length=225), nullable=True),
    sa.Column('political_appearance_name', sa.String(length=225), nullable=True),
    sa.Column('student_type', sa.String(length=225), nullable=True),
    sa.Column('departments', sa.String(length=225), nullable=True),
    sa.Column('education__time', sa.String(length=225), nullable=True),
    sa.Column('source_provinces', sa.String(length=225), nullable=True),
    sa.Column('offer_volunteer', sa.String(length=225), nullable=True),
    sa.Column('Professional_1', sa.String(length=225), nullable=True),
    sa.Column('Professional_2', sa.String(length=225), nullable=True),
    sa.Column('Professional_3', sa.String(length=225), nullable=True),
    sa.Column('Professional_4', sa.String(length=225), nullable=True),
    sa.Column('Professional_5', sa.String(length=225), nullable=True),
    sa.Column('Professional_6', sa.String(length=225), nullable=True),
    sa.Column('zsyear', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['zsyear'], ['record.zsyear'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('stu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stu',
    sa.Column('sid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('NAME', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('sid'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('zs')
    op.drop_table('record')
    # ### end Alembic commands ###
